on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: run test
    steps:
    - name: run test in docker
      uses: onihusube/gcc-meson-docker-action@test5
      with:
        name: 'harmony'
        uri: 'https://github.com/onihusube/harmony.git'
