name: 'build & test'
on: [push, pull_request]

inputs:
    test-entry:
        description: 'meson build & run test'
        required: true
outputs:
    test-result:
        description: 'boost.ut & meson test report'

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.test-entry }}
